---
    
- name: Copy Static HTML File
  copy:
      src: static.html
      dest: /var/www/html/index.html

- name: Update Dynamic page
  template:
    src: dynamic.jinja2  
    dest: /var/www/html/dynam.html  
...